project_name: github-flow-manager

builds:
  - binary: github-flow-manager
    env:
      - CGO_ENABLED=0
    ldflags: -w -extldflags "-static"
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - format_overrides:
      - goos: windows
        format: zip
    builds:
      - github-flow-manager
    replacements:
      amd64: 64-bit
      darwin: macOS

nfpms:
  - id: github-flow-manager
    builds:
      - github-flow-manager
    formats:
      - deb
    vendor: DocPlanner
    homepage: https://github.com/DoccPlanner/github-flow-manager
    maintainer: DevOps Team <devops@docplanner.com>
    description: Push commits between branches but just those which pass evaluation checks

dockers:
  - image_templates:
    - docplanner/github-flow-manager:{{ trimprefix .Tag "v" }}-amd64
    - ghcr.io/docplanner/github-flow-manager:{{ trimprefix .Tag "v" }}-amd64
    goarch: amd64
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
    - --platform=linux/amd64
    - --label=org.opencontainers.image.title={{ .ProjectName }}
    - --label=org.opencontainers.image.description={{ .ProjectName }}
    - --label=org.opencontainers.image.url=https://github.com/docplanner/github-flow-manager
    - --label=org.opencontainers.image.source=https://github.com/docplanner/github-flow-manager
    - --label=org.opencontainers.image.version={{ .Version }}
    - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
    - --label=org.opencontainers.image.revision={{ .FullCommit }}
    - --label=org.opencontainers.image.licenses=MIT
  - image_templates:
    - docplanner/github-flow-manager:{{ trimprefix .Tag "v" }}-arm64
    - ghcr.io/docplanner/github-flow-manager:{{ trimprefix .Tag "v" }}-arm64
    goarch: arm64
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
    - --platform=linux/arm64/v8
    - --label=org.opencontainers.image.title={{ .ProjectName }}
    - --label=org.opencontainers.image.description={{ .ProjectName }}
    - --label=org.opencontainers.image.url=https://github.com/docplanner/github-flow-manager
    - --label=org.opencontainers.image.source=https://github.com/docplanner/github-flow-manager
    - --label=org.opencontainers.image.version={{ .Version }}
    - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
    - --label=org.opencontainers.image.revision={{ .FullCommit }}
    - --label=org.opencontainers.image.licenses=MIT
docker_manifests:
  - name_template: docplanner/github-flow-manager:{{ trimprefix .Tag "v" }}
    image_templates:
    - docplanner/github-flow-manager:{{ trimprefix .Tag "v" }}-amd64
    - docplanner/github-flow-manager:{{ trimprefix .Tag "v" }}-arm64
  - name_template: docplanner/github-flow-manager:latest
    image_templates:
    - docplanner/github-flow-manager:{{ trimprefix .Tag "v" }}-amd64
    - docplanner/github-flow-manager:{{ trimprefix .Tag "v" }}-arm64
  - name_template: ghcr.io/docplanner/github-flow-manager:{{ trimprefix .Tag "v" }}
    image_templates:
    - ghcr.io/docplanner/github-flow-manager:{{ trimprefix .Tag "v" }}-amd64
    - ghcr.io/docplanner/github-flow-manager:{{ trimprefix .Tag "v" }}-arm64
  - name_template: ghcr.io/docplanner/github-flow-manager:latest
    image_templates:
    - ghcr.io/docplanner/github-flow-manager:{{ trimprefix .Tag "v" }}-amd64
    - ghcr.io/docplanner/github-flow-manager:{{ trimprefix .Tag "v" }}-arm64
