builds:
  - binary: github-flow-manager
    env:
      - CGO_ENABLED=0
    ldflags: -w -extldflags "-static"
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
dockers:
  - image_templates:
    - docplanner/github-flow-manager